trigger:
- main

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'top-spring-boot-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile